### ISSUE TITLE
Is there API to replace thumbnail of a Book

### ISSUE THREAD

**Issue by shashikiranraifox** [vedavaapi/vedavaapi_api#5]
Is there an API to replace the thumbnail of a book. The existing API [POST /resources/{id}/files] does not remove the old thumbnail. It just adds one more thumbnail to the list of thumbnails already uploaded for the book. This would not be efficient.
Let me know the if there is an API, preferably I would like to avoid having to make a DELETE and POST request to replace a Book Thumbnail.

**Comment by damooo** [comment]
that api is only for linking new files to an object anna.
for operations over single file, we have `/files` operations.


1. `/files/<file_id>` `GET` will retrieve file. this is unique url for that file(/image). we are using iiif url instead of this for only `images`.
2. `/files/<file_id>` `POST` will update a file (or replaces/swaps) with new file. this is what we use for above requirement. it can be page image, or thumbnail image or any file, just swap that file pointed by that file_id at this centralized endpoint.
3. `/files/<file_id>` `DELETE` will delete that file

**Comment by shashikiranraifox** [comment]
Thanks for the response.

**Comment by shashikiranraifox** [comment]
@damooo  I used the request POST /files/{file_id} to replace the file but after replacement, the File gets corrupted. I am unable to get the Updated Thumbnail image. Some Permission Issue.

Book Id: 5c528e5142b93b4c115ec9ed
File Id: 5c528e5842b93b4c115ec9ee
IIIF URL: 
https://api.vedavaapi.org/py/demo/iiif_image/v1/objstore/5c528e5842b93b4c115ec9ee/full/,150/0/default.png

Refer Attached screenshot

![image](https://user-images.githubusercontent.com/45028441/52267876-2a9c5b00-2960-11e9-853b-79bdb2515a33.png)

**Comment by damooo** [comment]
fixed.

**Comment by shashikiranraifox** [comment]
This API is working now.
